name: helia
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.4.0
  firebase_auth: 4.2.0
  cloud_firestore: 4.2.0
  firebase_storage: 11.0.7
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.2
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  http: ^0.13.5
  salomon_bottom_bar: ^3.3.1
  readmore: ^2.2.0
  syncfusion_flutter_datepicker: ^20.3.61
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  ticket_widget: ^0.0.1
  image_picker: ^0.8.6
  dio: ^4.0.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

